<?php

/*
|------------------------------------------------------------------
| RSBSA Enrollment Form (rev. 01-2024) - PDF overlay coordinate map
|------------------------------------------------------------------
| Coordinates in points; page is US Letter (612 x 792); origin top-left,
| y increases downward. Types: text | boxed (gap = cell pitch) | check | image.
| Positions finalized via the visual tuner.
*/

return [

    'template' => 'templates/rsbsa-template.pdf',
    'page' => ['w' => 612, 'h' => 792],
    'font' => ['family' => 'Helvetica', 'size' => 8],

    // Extra height (pt) added below a page so extra content fits WITHOUT overlap.
    // Page 2 gets a blank white strip at the bottom for the 2nd 2x2.
    'extend' => [1 => 140],

    'fields' => [
        'photo' => ['type' => 'image', 'page' => 1, 'x' => 434.7, 'y' => 11.7, 'w' => 120, 'h' => 120],
        // Second 2x2 for the client's INTERNAL copy (not the official DA layout).
        // Page 2 is full, so this sits at the bottom; position it via the layout editor.
        // Full duplicate of the top 2x2, vertically aligned with it (same x/width).
        'photo2' => ['type' => 'image', 'page' => 1, 'x' => 434.7, 'y' => 802, 'w' => 120, 'h' => 120],
        'pcn_1' => ['type' => 'boxed', 'page' => 1, 'x' => 125, 'y' => 99.7, 'gap' => 14],
        'pcn_2' => ['type' => 'boxed', 'page' => 1, 'x' => 204.7, 'y' => 100, 'gap' => 14],
        'pcn_3' => ['type' => 'boxed', 'page' => 1, 'x' => 285.7, 'y' => 99, 'gap' => 14],
        'pcn_4' => ['type' => 'boxed', 'page' => 1, 'x' => 366.7, 'y' => 100, 'gap' => 14],
        'trn' => ['type' => 'boxed', 'page' => 1, 'x' => 115, 'y' => 121.7, 'gap' => 17.3],
        'surname' => ['type' => 'text', 'page' => 1, 'x' => 106.4, 'y' => 164.7],
        'first_name' => ['type' => 'text', 'page' => 1, 'x' => 307.3, 'y' => 164],
        'middle_name' => ['type' => 'text', 'page' => 1, 'x' => 105.4, 'y' => 188.7],
        'no_middle_name' => ['type' => 'check', 'page' => 1, 'x' => 95, 'y' => 205],
        'extension_name' => ['type' => 'text', 'page' => 1, 'x' => 297.3, 'y' => 186],
        'no_extension_name' => ['type' => 'check', 'page' => 1, 'x' => 290, 'y' => 205],
        'sex_male' => ['type' => 'check', 'page' => 1, 'x' => 459, 'y' => 208],
        'sex_female' => ['type' => 'check', 'page' => 1, 'x' => 503, 'y' => 208.3],
        'perm_house' => ['type' => 'text', 'page' => 1, 'x' => 164, 'y' => 234],
        'perm_street' => ['type' => 'text', 'page' => 1, 'x' => 272.7, 'y' => 233.7],
        'perm_barangay' => ['type' => 'text', 'page' => 1, 'x' => 414.3, 'y' => 234],
        'perm_city' => ['type' => 'text', 'page' => 1, 'x' => 66, 'y' => 267],
        'perm_province' => ['type' => 'text', 'page' => 1, 'x' => 233, 'y' => 267],
        'perm_region' => ['type' => 'text', 'page' => 1, 'x' => 472, 'y' => 267],
        'dob_mm' => ['type' => 'boxed', 'page' => 1, 'x' => 62.7, 'y' => 386.3, 'gap' => 11],
        'dob_dd' => ['type' => 'boxed', 'page' => 1, 'x' => 110, 'y' => 387, 'gap' => 10],
        'dob_yyyy' => ['type' => 'boxed', 'page' => 1, 'x' => 146, 'y' => 387, 'gap' => 11],
        'place_birth_city' => ['type' => 'text', 'page' => 1, 'x' => 200, 'y' => 386],
        'place_birth_province' => ['type' => 'text', 'page' => 1, 'x' => 200, 'y' => 406],
        'mobile' => ['type' => 'boxed', 'page' => 1, 'x' => 382, 'y' => 383, 'gap' => 13],
        'mother_maiden_name' => ['type' => 'text', 'page' => 1, 'x' => 73, 'y' => 429],
        'spouse' => ['type' => 'text', 'page' => 1, 'x' => 73.3, 'y' => 504],
        'civil_single' => ['type' => 'check', 'page' => 1, 'x' => 67.7, 'y' => 465.7],
        'civil_married' => ['type' => 'check', 'page' => 1, 'x' => 67.3, 'y' => 479],
        'civil_widow' => ['type' => 'check', 'page' => 1, 'x' => 171.7, 'y' => 464.3],
        'civil_legally' => ['type' => 'check', 'page' => 1, 'x' => 171.7, 'y' => 479],
        'religion_christianity' => ['type' => 'check', 'page' => 1, 'x' => 68.7, 'y' => 566],
        'religion_islam' => ['type' => 'check', 'page' => 1, 'x' => 142.3, 'y' => 566],
        'religion_others' => ['type' => 'check', 'page' => 1, 'x' => 197, 'y' => 566],
        'religion_none' => ['type' => 'check', 'page' => 1, 'x' => 261.7, 'y' => 565.3],
        'edu_preschool' => ['type' => 'check', 'page' => 1, 'x' => 341, 'y' => 471],
        'edu_elementary' => ['type' => 'check', 'page' => 1, 'x' => 341, 'y' => 484.3],
        'edu_highschool_nonk12' => ['type' => 'check', 'page' => 1, 'x' => 341, 'y' => 497],
        'edu_juniorhigh' => ['type' => 'check', 'page' => 1, 'x' => 341, 'y' => 510],
        'edu_seniorhigh' => ['type' => 'check', 'page' => 1, 'x' => 440.7, 'y' => 471],
        'edu_college' => ['type' => 'check', 'page' => 1, 'x' => 440.7, 'y' => 484.3],
        'edu_postgrad' => ['type' => 'check', 'page' => 1, 'x' => 441.4, 'y' => 497.4],
        'edu_vocational' => ['type' => 'check', 'page' => 1, 'x' => 441, 'y' => 509.7],
        'edu_none' => ['type' => 'check', 'page' => 1, 'x' => 503.6, 'y' => 510],
        'id_type' => ['type' => 'text', 'page' => 1, 'x' => 412.3, 'y' => 545],
        'id_number' => ['type' => 'text', 'page' => 1, 'x' => 418, 'y' => 566.7],
        'prov_house' => ['type' => 'text', 'page' => 1, 'x' => 164, 'y' => 314],
        'prov_street' => ['type' => 'text', 'page' => 1, 'x' => 271, 'y' => 314],
        'prov_barangay' => ['type' => 'text', 'page' => 1, 'x' => 412, 'y' => 314],
        'prov_city' => ['type' => 'text', 'page' => 1, 'x' => 65, 'y' => 343],
        'prov_province' => ['type' => 'text', 'page' => 1, 'x' => 231, 'y' => 342],
        'prov_region' => ['type' => 'text', 'page' => 1, 'x' => 414, 'y' => 343],
        'owns_mobile_yes' => ['type' => 'check', 'page' => 1, 'x' => 500.7, 'y' => 409],
        'owns_mobile_no' => ['type' => 'check', 'page' => 1, 'x' => 532.3, 'y' => 408.3],
        'mobile_owner_name' => ['type' => 'text', 'page' => 1, 'x' => 338.6, 'y' => 430.7],
        'mobile_owner_relationship' => ['type' => 'text', 'page' => 1, 'x' => 449, 'y' => 429.7],
        // RSBSA number prints as XX-XX-XX-XXX-XXXXX. Cells 3,6,9,13 are pre-printed
        // dashes, so the number is split into 5 boxed groups that skip those cells.
        'rsbsa_g1' => ['type' => 'boxed', 'page' => 1, 'x' => 122.0, 'y' => 534, 'gap' => 10.85],
        'rsbsa_g2' => ['type' => 'boxed', 'page' => 1, 'x' => 154.5, 'y' => 534, 'gap' => 10.85],
        'rsbsa_g3' => ['type' => 'boxed', 'page' => 1, 'x' => 187.2, 'y' => 534, 'gap' => 10.85],
        'rsbsa_g4' => ['type' => 'boxed', 'page' => 1, 'x' => 219.8, 'y' => 534, 'gap' => 10.85],
        'rsbsa_g5' => ['type' => 'boxed', 'page' => 1, 'x' => 263.3, 'y' => 534, 'gap' => 10.85],
        'icc_yes' => ['type' => 'check', 'page' => 1, 'x' => 69.7, 'y' => 592],
        'icc_no' => ['type' => 'check', 'page' => 1, 'x' => 104.7, 'y' => 592.7],
        'icc_name' => ['type' => 'text', 'page' => 1, 'x' => 220.7, 'y' => 589.3],
        'pwd_yes' => ['type' => 'check', 'page' => 1, 'x' => 338.6, 'y' => 591.6],
        'pwd_no' => ['type' => 'check', 'page' => 1, 'x' => 376.7, 'y' => 592],
        'fourps_yes' => ['type' => 'check', 'page' => 1, 'x' => 451.7, 'y' => 595],
        'fourps_no' => ['type' => 'check', 'page' => 1, 'x' => 481.3, 'y' => 595.6],
        'fca_1' => ['type' => 'text', 'page' => 1, 'x' => 80.3, 'y' => 621],
        'fca_2' => ['type' => 'text', 'page' => 1, 'x' => 243, 'y' => 620.7],
        'fca_3' => ['type' => 'text', 'page' => 1, 'x' => 405.7, 'y' => 620.7],
        'liv_farmer' => ['type' => 'check', 'page' => 1, 'x' => 70.7, 'y' => 664.3],
        'liv_worker' => ['type' => 'check', 'page' => 1, 'x' => 180.7, 'y' => 664],
        'liv_fisher' => ['type' => 'check', 'page' => 1, 'x' => 372.7, 'y' => 663.7],
        'liv_youth' => ['type' => 'check', 'page' => 1, 'x' => 483.3, 'y' => 664.3],
        'p1_barangay' => ['type' => 'text', 'page' => 2, 'x' => 112.3, 'y' => 86],
        'p1_city' => ['type' => 'text', 'page' => 2, 'x' => 79.7, 'y' => 99],
        'p1_area' => ['type' => 'text', 'page' => 2, 'x' => 156.3, 'y' => 115.7],
        'p1_ad_yes' => ['type' => 'check', 'page' => 2, 'x' => 158.3, 'y' => 124.3],
        'p1_ad_no' => ['type' => 'check', 'page' => 2, 'x' => 176.3, 'y' => 125.3],
        'p1_arb_yes' => ['type' => 'check', 'page' => 2, 'x' => 159, 'y' => 132.7],
        'p1_arb_no' => ['type' => 'check', 'page' => 2, 'x' => 176.7, 'y' => 133],
        'p1_own_registered' => ['type' => 'check', 'page' => 2, 'x' => 78, 'y' => 165],
        'p1_own_tenant' => ['type' => 'check', 'page' => 2, 'x' => 77.7, 'y' => 172.7],
        'p1_own_lessee' => ['type' => 'check', 'page' => 2, 'x' => 143.3, 'y' => 165],
        'p1_own_others' => ['type' => 'check', 'page' => 2, 'x' => 143.3, 'y' => 172.7],
        'p1_land_owner' => ['type' => 'text', 'page' => 2, 'x' => 127.7, 'y' => 180.3],
        'p1_tiller_name' => ['type' => 'text', 'page' => 2, 'x' => 362, 'y' => 205],
        'p1_remarks' => ['type' => 'text', 'page' => 2, 'x' => 480.7, 'y' => 209.7],
        'p1_c1_schedule' => ['type' => 'text', 'page' => 2, 'x' => 242, 'y' => 91.3],
        'p1_c1_commodity' => ['type' => 'text', 'page' => 2, 'x' => 316.7, 'y' => 90.7],
        'p1_c1_size' => ['type' => 'text', 'page' => 2, 'x' => 396.3, 'y' => 89.3],
        'p1_c1_heads' => ['type' => 'text', 'page' => 2, 'x' => 421.3, 'y' => 89.3],
        'p1_c2_schedule' => ['type' => 'text', 'page' => 2, 'x' => 242.7, 'y' => 110.3],
        'p1_c2_commodity' => ['type' => 'text', 'page' => 2, 'x' => 318, 'y' => 109],
        'p1_c2_size' => ['type' => 'text', 'page' => 2, 'x' => 395, 'y' => 112.3],
        'p1_c2_heads' => ['type' => 'text', 'page' => 2, 'x' => 425.7, 'y' => 111.7],
        'p2_barangay' => ['type' => 'text', 'page' => 2, 'x' => 112.3, 'y' => 236],
        'p2_city' => ['type' => 'text', 'page' => 2, 'x' => 79.7, 'y' => 249],
        'p2_area' => ['type' => 'text', 'page' => 2, 'x' => 156.3, 'y' => 265.7],
        'p2_ad_yes' => ['type' => 'check', 'page' => 2, 'x' => 158.3, 'y' => 274.3],
        'p2_ad_no' => ['type' => 'check', 'page' => 2, 'x' => 176.3, 'y' => 275.3],
        'p2_arb_yes' => ['type' => 'check', 'page' => 2, 'x' => 159, 'y' => 282.7],
        'p2_arb_no' => ['type' => 'check', 'page' => 2, 'x' => 176.7, 'y' => 283],
        'p2_own_registered' => ['type' => 'check', 'page' => 2, 'x' => 78, 'y' => 315],
        'p2_own_tenant' => ['type' => 'check', 'page' => 2, 'x' => 77.7, 'y' => 322.7],
        'p2_own_lessee' => ['type' => 'check', 'page' => 2, 'x' => 143.3, 'y' => 315],
        'p2_own_others' => ['type' => 'check', 'page' => 2, 'x' => 143.3, 'y' => 322.7],
        'p2_land_owner' => ['type' => 'text', 'page' => 2, 'x' => 127.7, 'y' => 330.3],
        'p2_tiller_name' => ['type' => 'text', 'page' => 2, 'x' => 362, 'y' => 355],
        'p2_remarks' => ['type' => 'text', 'page' => 2, 'x' => 480.7, 'y' => 359.7],
        'p2_c1_schedule' => ['type' => 'text', 'page' => 2, 'x' => 242, 'y' => 241.3],
        'p2_c1_commodity' => ['type' => 'text', 'page' => 2, 'x' => 316.7, 'y' => 240.7],
        'p2_c1_size' => ['type' => 'text', 'page' => 2, 'x' => 396.3, 'y' => 239.3],
        'p2_c1_heads' => ['type' => 'text', 'page' => 2, 'x' => 421.3, 'y' => 239.3],
        'p2_c2_schedule' => ['type' => 'text', 'page' => 2, 'x' => 242.7, 'y' => 260.3],
        'p2_c2_commodity' => ['type' => 'text', 'page' => 2, 'x' => 318, 'y' => 259],
        'p2_c2_size' => ['type' => 'text', 'page' => 2, 'x' => 395, 'y' => 262.3],
        'p2_c2_heads' => ['type' => 'text', 'page' => 2, 'x' => 425.7, 'y' => 261.7],
        'p3_barangay' => ['type' => 'text', 'page' => 2, 'x' => 112.3, 'y' => 386],
        'p3_city' => ['type' => 'text', 'page' => 2, 'x' => 79.7, 'y' => 399],
        'p3_area' => ['type' => 'text', 'page' => 2, 'x' => 156.3, 'y' => 415.7],
        'p3_ad_yes' => ['type' => 'check', 'page' => 2, 'x' => 158.3, 'y' => 424.3],
        'p3_ad_no' => ['type' => 'check', 'page' => 2, 'x' => 176.3, 'y' => 425.3],
        'p3_arb_yes' => ['type' => 'check', 'page' => 2, 'x' => 159, 'y' => 432.7],
        'p3_arb_no' => ['type' => 'check', 'page' => 2, 'x' => 176.7, 'y' => 433],
        'p3_own_registered' => ['type' => 'check', 'page' => 2, 'x' => 78, 'y' => 465],
        'p3_own_tenant' => ['type' => 'check', 'page' => 2, 'x' => 77.7, 'y' => 472.7],
        'p3_own_lessee' => ['type' => 'check', 'page' => 2, 'x' => 143.3, 'y' => 465],
        'p3_own_others' => ['type' => 'check', 'page' => 2, 'x' => 143.3, 'y' => 472.7],
        'p3_land_owner' => ['type' => 'text', 'page' => 2, 'x' => 127.7, 'y' => 480.3],
        'p3_tiller_name' => ['type' => 'text', 'page' => 2, 'x' => 362, 'y' => 505],
        'p3_remarks' => ['type' => 'text', 'page' => 2, 'x' => 480.7, 'y' => 509.7],
        'p3_c1_schedule' => ['type' => 'text', 'page' => 2, 'x' => 242, 'y' => 391.3],
        'p3_c1_commodity' => ['type' => 'text', 'page' => 2, 'x' => 316.7, 'y' => 390.7],
        'p3_c1_size' => ['type' => 'text', 'page' => 2, 'x' => 396.3, 'y' => 389.3],
        'p3_c1_heads' => ['type' => 'text', 'page' => 2, 'x' => 421.3, 'y' => 389.3],
        'p3_c2_schedule' => ['type' => 'text', 'page' => 2, 'x' => 242.7, 'y' => 410.3],
        'p3_c2_commodity' => ['type' => 'text', 'page' => 2, 'x' => 318, 'y' => 409],
        'p3_c2_size' => ['type' => 'text', 'page' => 2, 'x' => 395, 'y' => 412.3],
        'p3_c2_heads' => ['type' => 'text', 'page' => 2, 'x' => 425.7, 'y' => 411.7],

        // Parcel + rotational-tiller RSBSA numbers (system-generated) — tune in the layout editor
        'p1_parcel_rsbsa' => ['type' => 'boxed', 'page' => 2, 'x' => 127.5, 'y' => 194, 'gap' => 6.0],
        'p1_tiller_rsbsa' => ['type' => 'boxed', 'page' => 2, 'x' => 296.5, 'y' => 213, 'gap' => 7.3],
        'p2_parcel_rsbsa' => ['type' => 'boxed', 'page' => 2, 'x' => 127.5, 'y' => 344, 'gap' => 6.0],
        'p2_tiller_rsbsa' => ['type' => 'boxed', 'page' => 2, 'x' => 296.5, 'y' => 363, 'gap' => 7.3],
        'p3_parcel_rsbsa' => ['type' => 'boxed', 'page' => 2, 'x' => 127.5, 'y' => 494, 'gap' => 6.0],
        'p3_tiller_rsbsa' => ['type' => 'boxed', 'page' => 2, 'x' => 296.5, 'y' => 513, 'gap' => 7.3],
    ],
];
